name: mydemo
description: "A new Flutter project."
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  connectivity: ^3.0.6
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  image_picker: ^0.8.4+1
  path: ^1.8.0
  supabase_flutter: ^0.2.5
  google_sign_in: ^6.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

 